USE [master]
GO

/****** Object:  Database [Sales]    Script Date: 21/02/2023 10:48:37 ******/
CREATE DATABASE [Sales]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Sales', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Sales.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Sales_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Sales_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Sales].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Sales] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Sales] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Sales] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Sales] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Sales] SET ARITHABORT OFF 
GO

ALTER DATABASE [Sales] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Sales] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Sales] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Sales] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Sales] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Sales] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Sales] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Sales] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Sales] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Sales] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Sales] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Sales] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Sales] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Sales] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Sales] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Sales] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Sales] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Sales] SET RECOVERY FULL 
GO

ALTER DATABASE [Sales] SET  MULTI_USER 
GO

ALTER DATABASE [Sales] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Sales] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Sales] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Sales] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Sales] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Sales] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Sales] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Sales] SET  READ_WRITE 
GO

